### ISSUE TITLE
couldn't find build

### ISSUE THREAD

**Issue by vejbuch** [Morabotti/twitch-play-sound#1]
Error: ENOENT: no such file or directory, stat '/home/ubuntu/twitch-play-sound/client/build/index.html'

**Comment by Morabotti** [comment]
I think this is because you didn't build your front-end. You can do this by running `npm run build` in `/client` folder or running `npm run production` in `/server` folder.

**Comment by vejbuch** [comment]
So sorry, i tried on raspberry pi 4 with Arm and doesn't work. On Intel x86 works fine.
